/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-01-27 at 22:53:31 UTC 
 * Modify at your own risk.
 */

package com.usipitwe.api.usipitweAndroidApi.model;

/**
 * Model definition for AndroidDeviceOptions.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the usipitweAndroidApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AndroidDeviceOptions extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String androidDeviceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String buildManufacturer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String buildModel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gcmRegistrationId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AndroidNetworkOptions networkOptions;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAndroidDeviceId() {
    return androidDeviceId;
  }

  /**
   * @param androidDeviceId androidDeviceId or {@code null} for none
   */
  public AndroidDeviceOptions setAndroidDeviceId(java.lang.String androidDeviceId) {
    this.androidDeviceId = androidDeviceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBuildManufacturer() {
    return buildManufacturer;
  }

  /**
   * @param buildManufacturer buildManufacturer or {@code null} for none
   */
  public AndroidDeviceOptions setBuildManufacturer(java.lang.String buildManufacturer) {
    this.buildManufacturer = buildManufacturer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBuildModel() {
    return buildModel;
  }

  /**
   * @param buildModel buildModel or {@code null} for none
   */
  public AndroidDeviceOptions setBuildModel(java.lang.String buildModel) {
    this.buildModel = buildModel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }

  /**
   * @param deviceId deviceId or {@code null} for none
   */
  public AndroidDeviceOptions setDeviceId(java.lang.String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGcmRegistrationId() {
    return gcmRegistrationId;
  }

  /**
   * @param gcmRegistrationId gcmRegistrationId or {@code null} for none
   */
  public AndroidDeviceOptions setGcmRegistrationId(java.lang.String gcmRegistrationId) {
    this.gcmRegistrationId = gcmRegistrationId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public AndroidNetworkOptions getNetworkOptions() {
    return networkOptions;
  }

  /**
   * @param networkOptions networkOptions or {@code null} for none
   */
  public AndroidDeviceOptions setNetworkOptions(AndroidNetworkOptions networkOptions) {
    this.networkOptions = networkOptions;
    return this;
  }

  @Override
  public AndroidDeviceOptions set(String fieldName, Object value) {
    return (AndroidDeviceOptions) super.set(fieldName, value);
  }

  @Override
  public AndroidDeviceOptions clone() {
    return (AndroidDeviceOptions) super.clone();
  }

}
