/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-01-27 at 22:53:31 UTC 
 * Modify at your own risk.
 */

package com.usipitwe.api.usipitweAndroidApi.model;

/**
 * Model definition for AndroidNetworkOptions.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the usipitweAndroidApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AndroidNetworkOptions extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String networkCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String networkCountryCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String networkOperator;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String networkOperatorName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String simCountryCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String simOperatorName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String simSerialNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String subscriberId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNetworkCode() {
    return networkCode;
  }

  /**
   * @param networkCode networkCode or {@code null} for none
   */
  public AndroidNetworkOptions setNetworkCode(java.lang.String networkCode) {
    this.networkCode = networkCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNetworkCountryCode() {
    return networkCountryCode;
  }

  /**
   * @param networkCountryCode networkCountryCode or {@code null} for none
   */
  public AndroidNetworkOptions setNetworkCountryCode(java.lang.String networkCountryCode) {
    this.networkCountryCode = networkCountryCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNetworkOperator() {
    return networkOperator;
  }

  /**
   * @param networkOperator networkOperator or {@code null} for none
   */
  public AndroidNetworkOptions setNetworkOperator(java.lang.String networkOperator) {
    this.networkOperator = networkOperator;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNetworkOperatorName() {
    return networkOperatorName;
  }

  /**
   * @param networkOperatorName networkOperatorName or {@code null} for none
   */
  public AndroidNetworkOptions setNetworkOperatorName(java.lang.String networkOperatorName) {
    this.networkOperatorName = networkOperatorName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSimCountryCode() {
    return simCountryCode;
  }

  /**
   * @param simCountryCode simCountryCode or {@code null} for none
   */
  public AndroidNetworkOptions setSimCountryCode(java.lang.String simCountryCode) {
    this.simCountryCode = simCountryCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSimOperatorName() {
    return simOperatorName;
  }

  /**
   * @param simOperatorName simOperatorName or {@code null} for none
   */
  public AndroidNetworkOptions setSimOperatorName(java.lang.String simOperatorName) {
    this.simOperatorName = simOperatorName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSimSerialNumber() {
    return simSerialNumber;
  }

  /**
   * @param simSerialNumber simSerialNumber or {@code null} for none
   */
  public AndroidNetworkOptions setSimSerialNumber(java.lang.String simSerialNumber) {
    this.simSerialNumber = simSerialNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSubscriberId() {
    return subscriberId;
  }

  /**
   * @param subscriberId subscriberId or {@code null} for none
   */
  public AndroidNetworkOptions setSubscriberId(java.lang.String subscriberId) {
    this.subscriberId = subscriberId;
    return this;
  }

  @Override
  public AndroidNetworkOptions set(String fieldName, Object value) {
    return (AndroidNetworkOptions) super.set(fieldName, value);
  }

  @Override
  public AndroidNetworkOptions clone() {
    return (AndroidNetworkOptions) super.clone();
  }

}
