/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-01-27 at 22:53:31 UTC 
 * Modify at your own risk.
 */

package com.usipitwe.api.usipitweAndroidApi.model;

/**
 * Model definition for AndroidDevice.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the usipitweAndroidApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AndroidDevice extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String androidBuildManufacturer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String androidBuildModel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime created;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gcmCanonicalRegistrationId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gcmRegistrationId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime modified;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAndroidBuildManufacturer() {
    return androidBuildManufacturer;
  }

  /**
   * @param androidBuildManufacturer androidBuildManufacturer or {@code null} for none
   */
  public AndroidDevice setAndroidBuildManufacturer(java.lang.String androidBuildManufacturer) {
    this.androidBuildManufacturer = androidBuildManufacturer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAndroidBuildModel() {
    return androidBuildModel;
  }

  /**
   * @param androidBuildModel androidBuildModel or {@code null} for none
   */
  public AndroidDevice setAndroidBuildModel(java.lang.String androidBuildModel) {
    this.androidBuildModel = androidBuildModel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreated() {
    return created;
  }

  /**
   * @param created created or {@code null} for none
   */
  public AndroidDevice setCreated(com.google.api.client.util.DateTime created) {
    this.created = created;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }

  /**
   * @param deviceId deviceId or {@code null} for none
   */
  public AndroidDevice setDeviceId(java.lang.String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGcmCanonicalRegistrationId() {
    return gcmCanonicalRegistrationId;
  }

  /**
   * @param gcmCanonicalRegistrationId gcmCanonicalRegistrationId or {@code null} for none
   */
  public AndroidDevice setGcmCanonicalRegistrationId(java.lang.String gcmCanonicalRegistrationId) {
    this.gcmCanonicalRegistrationId = gcmCanonicalRegistrationId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGcmRegistrationId() {
    return gcmRegistrationId;
  }

  /**
   * @param gcmRegistrationId gcmRegistrationId or {@code null} for none
   */
  public AndroidDevice setGcmRegistrationId(java.lang.String gcmRegistrationId) {
    this.gcmRegistrationId = gcmRegistrationId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getModified() {
    return modified;
  }

  /**
   * @param modified modified or {@code null} for none
   */
  public AndroidDevice setModified(com.google.api.client.util.DateTime modified) {
    this.modified = modified;
    return this;
  }

  @Override
  public AndroidDevice set(String fieldName, Object value) {
    return (AndroidDevice) super.set(fieldName, value);
  }

  @Override
  public AndroidDevice clone() {
    return (AndroidDevice) super.clone();
  }

}
