/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-01-27 at 22:53:31 UTC 
 * Modify at your own risk.
 */

package com.usipitwe.api.usipitweAndroidApi;

/**
 * Service definition for UsipitweAndroidApi (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UsipitweAndroidApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class UsipitweAndroidApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the usipitweAndroidApi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://usipitwe-app.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "usipitweAndroidApi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public UsipitweAndroidApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  UsipitweAndroidApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "deviceUpdate".
   *
   * This request holds the parameters needed by the usipitweAndroidApi server.  After setting any
   * optional parameters, call the {@link DeviceUpdate#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public DeviceUpdate deviceUpdate() throws java.io.IOException {
    DeviceUpdate result = new DeviceUpdate();
    initialize(result);
    return result;
  }

  public class DeviceUpdate extends UsipitweAndroidApiRequest<com.usipitwe.api.usipitweAndroidApi.model.RegistrationResponse> {

    private static final String REST_PATH = "deviceUpdate";

    /**
     * Create a request for the method "deviceUpdate".
     *
     * This request holds the parameters needed by the the usipitweAndroidApi server.  After setting
     * any optional parameters, call the {@link DeviceUpdate#execute()} method to invoke the remote
     * operation. <p> {@link
     * DeviceUpdate#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected DeviceUpdate() {
      super(UsipitweAndroidApi.this, "GET", REST_PATH, null, com.usipitwe.api.usipitweAndroidApi.model.RegistrationResponse.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public DeviceUpdate setAlt(java.lang.String alt) {
      return (DeviceUpdate) super.setAlt(alt);
    }

    @Override
    public DeviceUpdate setFields(java.lang.String fields) {
      return (DeviceUpdate) super.setFields(fields);
    }

    @Override
    public DeviceUpdate setKey(java.lang.String key) {
      return (DeviceUpdate) super.setKey(key);
    }

    @Override
    public DeviceUpdate setOauthToken(java.lang.String oauthToken) {
      return (DeviceUpdate) super.setOauthToken(oauthToken);
    }

    @Override
    public DeviceUpdate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DeviceUpdate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DeviceUpdate setQuotaUser(java.lang.String quotaUser) {
      return (DeviceUpdate) super.setQuotaUser(quotaUser);
    }

    @Override
    public DeviceUpdate setUserIp(java.lang.String userIp) {
      return (DeviceUpdate) super.setUserIp(userIp);
    }

    @Override
    public DeviceUpdate set(String parameterName, Object value) {
      return (DeviceUpdate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getSites".
   *
   * This request holds the parameters needed by the usipitweAndroidApi server.  After setting any
   * optional parameters, call the {@link GetSites#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetSites getSites() throws java.io.IOException {
    GetSites result = new GetSites();
    initialize(result);
    return result;
  }

  public class GetSites extends UsipitweAndroidApiRequest<com.usipitwe.api.usipitweAndroidApi.model.SiteCollection> {

    private static final String REST_PATH = "sitecollection";

    /**
     * Create a request for the method "getSites".
     *
     * This request holds the parameters needed by the the usipitweAndroidApi server.  After setting
     * any optional parameters, call the {@link GetSites#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetSites#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetSites() {
      super(UsipitweAndroidApi.this, "GET", REST_PATH, null, com.usipitwe.api.usipitweAndroidApi.model.SiteCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSites setAlt(java.lang.String alt) {
      return (GetSites) super.setAlt(alt);
    }

    @Override
    public GetSites setFields(java.lang.String fields) {
      return (GetSites) super.setFields(fields);
    }

    @Override
    public GetSites setKey(java.lang.String key) {
      return (GetSites) super.setKey(key);
    }

    @Override
    public GetSites setOauthToken(java.lang.String oauthToken) {
      return (GetSites) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSites setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSites) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSites setQuotaUser(java.lang.String quotaUser) {
      return (GetSites) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSites setUserIp(java.lang.String userIp) {
      return (GetSites) super.setUserIp(userIp);
    }

    @Override
    public GetSites set(String parameterName, Object value) {
      return (GetSites) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "queryLatestItems".
   *
   * This request holds the parameters needed by the usipitweAndroidApi server.  After setting any
   * optional parameters, call the {@link QueryLatestItems#execute()} method to invoke the remote
   * operation.
   *
   * @param limit
   * @return the request
   */
  public QueryLatestItems queryLatestItems(java.lang.Integer limit) throws java.io.IOException {
    QueryLatestItems result = new QueryLatestItems(limit);
    initialize(result);
    return result;
  }

  public class QueryLatestItems extends UsipitweAndroidApiRequest<com.usipitwe.api.usipitweAndroidApi.model.ItemCollection> {

    private static final String REST_PATH = "queryLatestItems/{limit}";

    /**
     * Create a request for the method "queryLatestItems".
     *
     * This request holds the parameters needed by the the usipitweAndroidApi server.  After setting
     * any optional parameters, call the {@link QueryLatestItems#execute()} method to invoke the
     * remote operation. <p> {@link QueryLatestItems#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param limit
     * @since 1.13
     */
    protected QueryLatestItems(java.lang.Integer limit) {
      super(UsipitweAndroidApi.this, "GET", REST_PATH, null, com.usipitwe.api.usipitweAndroidApi.model.ItemCollection.class);
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public QueryLatestItems setAlt(java.lang.String alt) {
      return (QueryLatestItems) super.setAlt(alt);
    }

    @Override
    public QueryLatestItems setFields(java.lang.String fields) {
      return (QueryLatestItems) super.setFields(fields);
    }

    @Override
    public QueryLatestItems setKey(java.lang.String key) {
      return (QueryLatestItems) super.setKey(key);
    }

    @Override
    public QueryLatestItems setOauthToken(java.lang.String oauthToken) {
      return (QueryLatestItems) super.setOauthToken(oauthToken);
    }

    @Override
    public QueryLatestItems setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (QueryLatestItems) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QueryLatestItems setQuotaUser(java.lang.String quotaUser) {
      return (QueryLatestItems) super.setQuotaUser(quotaUser);
    }

    @Override
    public QueryLatestItems setUserIp(java.lang.String userIp) {
      return (QueryLatestItems) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public QueryLatestItems setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public QueryLatestItems set(String parameterName, Object value) {
      return (QueryLatestItems) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "querySiteLatestItems".
   *
   * This request holds the parameters needed by the usipitweAndroidApi server.  After setting any
   * optional parameters, call the {@link QuerySiteLatestItems#execute()} method to invoke the remote
   * operation.
   *
   * @param siteId
   * @param limit
   * @return the request
   */
  public QuerySiteLatestItems querySiteLatestItems(java.lang.String siteId, java.lang.Integer limit) throws java.io.IOException {
    QuerySiteLatestItems result = new QuerySiteLatestItems(siteId, limit);
    initialize(result);
    return result;
  }

  public class QuerySiteLatestItems extends UsipitweAndroidApiRequest<com.usipitwe.api.usipitweAndroidApi.model.ItemCollection> {

    private static final String REST_PATH = "querySiteLatestItems/{siteId}/{limit}";

    /**
     * Create a request for the method "querySiteLatestItems".
     *
     * This request holds the parameters needed by the the usipitweAndroidApi server.  After setting
     * any optional parameters, call the {@link QuerySiteLatestItems#execute()} method to invoke the
     * remote operation. <p> {@link QuerySiteLatestItems#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param siteId
     * @param limit
     * @since 1.13
     */
    protected QuerySiteLatestItems(java.lang.String siteId, java.lang.Integer limit) {
      super(UsipitweAndroidApi.this, "GET", REST_PATH, null, com.usipitwe.api.usipitweAndroidApi.model.ItemCollection.class);
      this.siteId = com.google.api.client.util.Preconditions.checkNotNull(siteId, "Required parameter siteId must be specified.");
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public QuerySiteLatestItems setAlt(java.lang.String alt) {
      return (QuerySiteLatestItems) super.setAlt(alt);
    }

    @Override
    public QuerySiteLatestItems setFields(java.lang.String fields) {
      return (QuerySiteLatestItems) super.setFields(fields);
    }

    @Override
    public QuerySiteLatestItems setKey(java.lang.String key) {
      return (QuerySiteLatestItems) super.setKey(key);
    }

    @Override
    public QuerySiteLatestItems setOauthToken(java.lang.String oauthToken) {
      return (QuerySiteLatestItems) super.setOauthToken(oauthToken);
    }

    @Override
    public QuerySiteLatestItems setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (QuerySiteLatestItems) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QuerySiteLatestItems setQuotaUser(java.lang.String quotaUser) {
      return (QuerySiteLatestItems) super.setQuotaUser(quotaUser);
    }

    @Override
    public QuerySiteLatestItems setUserIp(java.lang.String userIp) {
      return (QuerySiteLatestItems) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String siteId;

    /**

     */
    public java.lang.String getSiteId() {
      return siteId;
    }

    public QuerySiteLatestItems setSiteId(java.lang.String siteId) {
      this.siteId = siteId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public QuerySiteLatestItems setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public QuerySiteLatestItems set(String parameterName, Object value) {
      return (QuerySiteLatestItems) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "querySiteTopItems".
   *
   * This request holds the parameters needed by the usipitweAndroidApi server.  After setting any
   * optional parameters, call the {@link QuerySiteTopItems#execute()} method to invoke the remote
   * operation.
   *
   * @param siteId
   * @param limit
   * @return the request
   */
  public QuerySiteTopItems querySiteTopItems(java.lang.String siteId, java.lang.Integer limit) throws java.io.IOException {
    QuerySiteTopItems result = new QuerySiteTopItems(siteId, limit);
    initialize(result);
    return result;
  }

  public class QuerySiteTopItems extends UsipitweAndroidApiRequest<com.usipitwe.api.usipitweAndroidApi.model.ItemCollection> {

    private static final String REST_PATH = "querySiteTopItems/{siteId}/{limit}";

    /**
     * Create a request for the method "querySiteTopItems".
     *
     * This request holds the parameters needed by the the usipitweAndroidApi server.  After setting
     * any optional parameters, call the {@link QuerySiteTopItems#execute()} method to invoke the
     * remote operation. <p> {@link QuerySiteTopItems#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param siteId
     * @param limit
     * @since 1.13
     */
    protected QuerySiteTopItems(java.lang.String siteId, java.lang.Integer limit) {
      super(UsipitweAndroidApi.this, "GET", REST_PATH, null, com.usipitwe.api.usipitweAndroidApi.model.ItemCollection.class);
      this.siteId = com.google.api.client.util.Preconditions.checkNotNull(siteId, "Required parameter siteId must be specified.");
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public QuerySiteTopItems setAlt(java.lang.String alt) {
      return (QuerySiteTopItems) super.setAlt(alt);
    }

    @Override
    public QuerySiteTopItems setFields(java.lang.String fields) {
      return (QuerySiteTopItems) super.setFields(fields);
    }

    @Override
    public QuerySiteTopItems setKey(java.lang.String key) {
      return (QuerySiteTopItems) super.setKey(key);
    }

    @Override
    public QuerySiteTopItems setOauthToken(java.lang.String oauthToken) {
      return (QuerySiteTopItems) super.setOauthToken(oauthToken);
    }

    @Override
    public QuerySiteTopItems setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (QuerySiteTopItems) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QuerySiteTopItems setQuotaUser(java.lang.String quotaUser) {
      return (QuerySiteTopItems) super.setQuotaUser(quotaUser);
    }

    @Override
    public QuerySiteTopItems setUserIp(java.lang.String userIp) {
      return (QuerySiteTopItems) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String siteId;

    /**

     */
    public java.lang.String getSiteId() {
      return siteId;
    }

    public QuerySiteTopItems setSiteId(java.lang.String siteId) {
      this.siteId = siteId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public QuerySiteTopItems setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public QuerySiteTopItems set(String parameterName, Object value) {
      return (QuerySiteTopItems) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "queryTopItems".
   *
   * This request holds the parameters needed by the usipitweAndroidApi server.  After setting any
   * optional parameters, call the {@link QueryTopItems#execute()} method to invoke the remote
   * operation.
   *
   * @param limit
   * @return the request
   */
  public QueryTopItems queryTopItems(java.lang.Integer limit) throws java.io.IOException {
    QueryTopItems result = new QueryTopItems(limit);
    initialize(result);
    return result;
  }

  public class QueryTopItems extends UsipitweAndroidApiRequest<com.usipitwe.api.usipitweAndroidApi.model.ItemCollection> {

    private static final String REST_PATH = "queryTopItems/{limit}";

    /**
     * Create a request for the method "queryTopItems".
     *
     * This request holds the parameters needed by the the usipitweAndroidApi server.  After setting
     * any optional parameters, call the {@link QueryTopItems#execute()} method to invoke the remote
     * operation. <p> {@link QueryTopItems#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param limit
     * @since 1.13
     */
    protected QueryTopItems(java.lang.Integer limit) {
      super(UsipitweAndroidApi.this, "GET", REST_PATH, null, com.usipitwe.api.usipitweAndroidApi.model.ItemCollection.class);
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public QueryTopItems setAlt(java.lang.String alt) {
      return (QueryTopItems) super.setAlt(alt);
    }

    @Override
    public QueryTopItems setFields(java.lang.String fields) {
      return (QueryTopItems) super.setFields(fields);
    }

    @Override
    public QueryTopItems setKey(java.lang.String key) {
      return (QueryTopItems) super.setKey(key);
    }

    @Override
    public QueryTopItems setOauthToken(java.lang.String oauthToken) {
      return (QueryTopItems) super.setOauthToken(oauthToken);
    }

    @Override
    public QueryTopItems setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (QueryTopItems) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QueryTopItems setQuotaUser(java.lang.String quotaUser) {
      return (QueryTopItems) super.setQuotaUser(quotaUser);
    }

    @Override
    public QueryTopItems setUserIp(java.lang.String userIp) {
      return (QueryTopItems) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public QueryTopItems setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public QueryTopItems set(String parameterName, Object value) {
      return (QueryTopItems) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link UsipitweAndroidApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link UsipitweAndroidApi}. */
    @Override
    public UsipitweAndroidApi build() {
      return new UsipitweAndroidApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UsipitweAndroidApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUsipitweAndroidApiRequestInitializer(
        UsipitweAndroidApiRequestInitializer usipitweandroidapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(usipitweandroidapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
