/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-01-27 at 22:53:31 UTC 
 * Modify at your own risk.
 */

package com.usipitwe.api.usipitweAndroidApi.model;

/**
 * Model definition for Item.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the usipitweAndroidApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Item extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime created;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String domain;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer fbShares;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer gscore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double heat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pictureUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime pubDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String siteId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer tweets;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreated() {
    return created;
  }

  /**
   * @param created created or {@code null} for none
   */
  public Item setCreated(com.google.api.client.util.DateTime created) {
    this.created = created;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public Item setDate(com.google.api.client.util.DateTime date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDomain() {
    return domain;
  }

  /**
   * @param domain domain or {@code null} for none
   */
  public Item setDomain(java.lang.String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFbShares() {
    return fbShares;
  }

  /**
   * @param fbShares fbShares or {@code null} for none
   */
  public Item setFbShares(java.lang.Integer fbShares) {
    this.fbShares = fbShares;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getGscore() {
    return gscore;
  }

  /**
   * @param gscore gscore or {@code null} for none
   */
  public Item setGscore(java.lang.Integer gscore) {
    this.gscore = gscore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getHeat() {
    return heat;
  }

  /**
   * @param heat heat or {@code null} for none
   */
  public Item setHeat(java.lang.Double heat) {
    this.heat = heat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Item setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPictureUrl() {
    return pictureUrl;
  }

  /**
   * @param pictureUrl pictureUrl or {@code null} for none
   */
  public Item setPictureUrl(java.lang.String pictureUrl) {
    this.pictureUrl = pictureUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getPubDate() {
    return pubDate;
  }

  /**
   * @param pubDate pubDate or {@code null} for none
   */
  public Item setPubDate(com.google.api.client.util.DateTime pubDate) {
    this.pubDate = pubDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSiteId() {
    return siteId;
  }

  /**
   * @param siteId siteId or {@code null} for none
   */
  public Item setSiteId(java.lang.String siteId) {
    this.siteId = siteId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public Item setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTweets() {
    return tweets;
  }

  /**
   * @param tweets tweets or {@code null} for none
   */
  public Item setTweets(java.lang.Integer tweets) {
    this.tweets = tweets;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * @param url url or {@code null} for none
   */
  public Item setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  @Override
  public Item set(String fieldName, Object value) {
    return (Item) super.set(fieldName, value);
  }

  @Override
  public Item clone() {
    return (Item) super.clone();
  }

}
